[package]
name = "generics"
version = "0.0.3"
description = "Helper for asynchronous generics"
repository = "https://github.com/research-ag/generics"
keywords = [ "async", "parametric", "type", "parameter" ]
license = "Apache-2.0"

[dependencies]
core = "2.0.0"

[dev-dependencies]
bench = "1.0.0"

[toolchain]
moc = "1.0.0"

[requirements]
moc = "1.0.0"
